// AUTHORED-BY Claude Opus 4.8 (Fable unavailable) — re-review/upgrade candidate.
/**
 * Vocabulary IRIs for the shared multi-intolerance health-diary model.
 *
 * **Reuse established, dereferenceable terms; mint only the genuinely-missing
 * nutrition/intolerance concepts under `diet:`.** Per the coeliac-app DESIGN §2.1
 * (extend the existing gUFO-rooted `health` sector, do NOT fork it) and the
 * suite's federation-namespace discipline:
 *
 * - **`schema:` — schema.org** (canonical `http://` scheme): `schema:FoodEvent`
 *   (the super-class of `diet:Meal` — a real schema.org type, `⊑ schema:Event`;
 *   note schema.org has NO `schema:Meal`), `schema:name`, `schema:startTime`,
 *   `schema:endTime`, `schema:location`, `schema:image`.
 * - **`health:` — the suite health sector** (`https://w3id.org/jeswr/sectors/health#`,
 *   FHIR/SNOMED/LOINC-aligned, gUFO-rooted): `health:Patient` (the pod owner),
 *   `health:Observation` (the super-class a `diet:Symptom` is stamped with).
 * - **`core:` — the suite gUFO core** (`https://w3id.org/jeswr/core#`): `core:about`
 *   links a record entry to the `health:Patient` it concerns (each diary entry is
 *   `core:about` the pod-owner Patient — DESIGN §2.2).
 * - **`prov:` — W3C PROV-O**: `prov:wasDerivedFrom` (an Exposure/Conclusion is
 *   derived from the FoodItems/exposures/protocol it rests on),
 *   `prov:wasGeneratedBy` (a scan generated by the OFF lookup).
 * - **`dcterms:` — Dublin Core Terms**: `dcterms:created`, `dcterms:modified`,
 *   `dcterms:source`.
 * - **`acl:` — W3C ACL** for the owner-only fail-closed ACL helper (`./acl.ts`).
 * - **`skos:` — W3C SKOS**: `skos:Concept` (a TriggerClass / symptom type is a
 *   SKOS concept), `skos:prefLabel`.
 *
 * ### `diet:` — the new nutrition/intolerance namespace
 * `https://w3id.org/jeswr/sectors/health/diet#` — a SUB-MODULE of the health
 * sector (so it inherits Core-rooting). The formal ontology + SHACL are authored
 * in `solid-federation-vocab` (coeliac-app Brief 1B) **in parallel**; this package
 * uses the term IRIs DESIGN §2.2 specifies. Where DESIGN named a concept but not
 * its exact IRI form, the term is marked `INVENTED (1B-reconcile)` below and
 * listed in the package's hand-off report so 1B and this package converge before
 * the committed `dist/` is treated as final. The w3id redirect for the namespace
 * is a `needs:user` item.
 */

// --- Namespaces ---------------------------------------------------------------

/** schema.org (canonical http scheme) — `schema:FoodEvent`, `schema:startTime`, … */
export const SCHEMA = "http://schema.org/";
/** The suite health sector — `health:Patient`, `health:Observation`. */
export const HEALTH = "https://w3id.org/jeswr/sectors/health#";
/** The suite gUFO core — `core:about` (record → the Person/Patient it concerns). */
export const CORE = "https://w3id.org/jeswr/core#";
/**
 * The NEW nutrition/intolerance namespace, a sub-module of the health sector.
 * Formal ontology authored in `solid-federation-vocab` (Brief 1B); w3id redirect
 * is a `needs:user` item.
 */
export const DIET = "https://w3id.org/jeswr/sectors/health/diet#";
/** W3C PROV-O — `prov:wasDerivedFrom`, `prov:wasGeneratedBy`. */
export const PROV = "http://www.w3.org/ns/prov#";
/** Dublin Core Terms — `dcterms:created`/`modified`/`source`. */
export const DCT = "http://purl.org/dc/terms/";
/** W3C ACL ontology — the owner-only ACL helper. */
export const ACL = "http://www.w3.org/ns/auth/acl#";
/** W3C SKOS — a TriggerClass / symptom type is a `skos:Concept`. */
export const SKOS = "http://www.w3.org/2004/02/skos/core#";
/** RDF — `rdf:type`. */
export const RDF = "http://www.w3.org/1999/02/22-rdf-syntax-ns#";
/** RDF Schema — `rdfs:label`. */
export const RDFS = "http://www.w3.org/2000/01/rdf-schema#";
/** XSD datatypes (referenced via the wrapper value mappers). */
export const XSD = "http://www.w3.org/2001/XMLSchema#";
/** FOAF — `foaf:Agent` (referenced only to prove its ABSENCE in the owner-only ACL). */
export const FOAF = "http://xmlns.com/foaf/0.1/";

// --- Term-IRI builders --------------------------------------------------------

/** Build a `schema:` term IRI (e.g. `schema:FoodEvent`, `schema:startTime`). */
export const schema = (local: string): string => `${SCHEMA}${local}`;
/** Build a `health:` term IRI. */
export const health = (local: string): string => `${HEALTH}${local}`;
/** Build a `core:` term IRI. */
export const core = (local: string): string => `${CORE}${local}`;
/** Build a `diet:` term IRI. */
export const diet = (local: string): string => `${DIET}${local}`;
/** Build a `prov:` term IRI. */
export const prov = (local: string): string => `${PROV}${local}`;
/** Build a `dcterms:` term IRI. */
export const dct = (local: string): string => `${DCT}${local}`;
/** Build an `acl:` term IRI. */
export const acl = (local: string): string => `${ACL}${local}`;
/** Build a `skos:` term IRI. */
export const skos = (local: string): string => `${SKOS}${local}`;
/** Build an `rdf:` term IRI. */
export const rdf = (local: string): string => `${RDF}${local}`;
/** Build an `rdfs:` term IRI. */
export const rdfs = (local: string): string => `${RDFS}${local}`;
/** Build an `xsd:` term IRI. */
export const xsd = (local: string): string => `${XSD}${local}`;

/** The `rdf:type` predicate IRI (convenience). */
export const RDF_TYPE = rdf("type");

// --- Reused class + property IRIs --------------------------------------------

/**
 * `schema:FoodEvent` — the super-class of `diet:Meal`. A real, dereferenceable
 * schema.org type (`schema:FoodEvent ⊑ schema:Event`) for an eating/intake event.
 * (schema.org has NO `schema:Meal` — that IRI 404s — so the earlier `SCHEMA_MEAL`
 * naming was corrected to this existing term.)
 */
export const SCHEMA_FOOD_EVENT = schema("FoodEvent");
/** `health:Patient` — the pod-owner role each entry is `core:about`. */
export const HEALTH_PATIENT = health("Patient");
/** `health:Observation` — the super-class a `diet:Symptom` is stamped with. */
export const HEALTH_OBSERVATION = health("Observation");
/** `core:about` — links a diary record to the Patient it concerns. */
export const CORE_ABOUT = core("about");
/** `core:Person` — the real-world person a `health:Patient` role is played by. */
export const CORE_PERSON = core("Person");
/**
 * `health:patient` — the pod-owner Person a record is about (a sub-property of
 * `core:about`). The diet SHACL checks a Symptom's patient link on THIS property.
 */
export const HEALTH_PATIENT_PROP = health("patient");
/** `prov:wasDerivedFrom` — the base provenance edge `diet:derivedFrom`/`diet:restsOn` refine. */
export const PROV_DERIVED_FROM = prov("wasDerivedFrom");
/** `prov:wasGeneratedBy` — a scanned FoodItem was generated by the OFF lookup activity. */
export const PROV_GENERATED_BY = prov("wasGeneratedBy");
/**
 * `diet:derivedFrom` — an Exposure/ToleranceConclusion's tap-through provenance
 * (a sub-property of `prov:wasDerivedFrom`; the diet SHACL checks THIS predicate).
 */
export const DIET_DERIVED_FROM = diet("derivedFrom");
/** `diet:restsOn` — a DietPlan's exclusion basis → a ToleranceConclusion (⊑ `prov:wasDerivedFrom`). */
export const DIET_RESTS_ON = diet("restsOn");
/** `skos:Concept` — the class of a TriggerClass / symptom-type concept. */
export const SKOS_CONCEPT = skos("Concept");

// --- `diet:` classes (DESIGN §2.2 — the nine entity classes) ------------------

/** `diet:Meal` (⊑ `schema:FoodEvent`) — an intake event. */
export const DIET_MEAL = diet("Meal");
/** `diet:FoodItem` — one food/product in a meal. */
export const DIET_FOOD_ITEM = diet("FoodItem");
/** `diet:Exposure` — the engine-derived trigger content of a meal. */
export const DIET_EXPOSURE = diet("Exposure");
/** `diet:Symptom` (⊑ `health:Observation`) — a symptom observation. */
export const DIET_SYMPTOM = diet("Symptom");
/** `diet:TriggerClass` (a `skos:Concept`) — a trigger with a lag profile. */
export const DIET_TRIGGER_CLASS = diet("TriggerClass");
/** `diet:EliminationProtocol` — the elimination/reintroduction state machine. */
export const DIET_ELIMINATION_PROTOCOL = diet("EliminationProtocol");
/** `diet:ToleranceConclusion` — a per-trigger tolerance verdict. */
export const DIET_TOLERANCE_CONCLUSION = diet("ToleranceConclusion");
/** `diet:GeneticSummary` — the interpreted HLA summary (raw file NEVER stored). */
export const DIET_GENETIC_SUMMARY = diet("GeneticSummary");
/** `diet:HlaMarker` — one interpreted HLA marker row within a GeneticSummary. */
export const DIET_HLA_MARKER = diet("HlaMarker");
/** `diet:DietPlan` — the current working exclusion set. */
export const DIET_DIET_PLAN = diet("DietPlan");

/**
 * Prefix map for an n3 `Writer` that serialises this model (pretty Turtle output).
 */
export const PREFIXES = {
  schema: SCHEMA,
  health: HEALTH,
  core: CORE,
  diet: DIET,
  prov: PROV,
  dcterms: DCT,
  acl: ACL,
  skos: SKOS,
  rdf: RDF,
  rdfs: RDFS,
} as const;

// --- TriggerClass + symptom concept IRIs -------------------------------------
//
// A TriggerClass and a symptom type are SKOS concepts (DESIGN §2.2 entities 4/5).
// DESIGN lists the SLUGS (gluten, lactose, …; bloating, diarrhoea, …) but not
// their IRI form, so the `diet:{slug}` concept IRIs minted here are
// INVENTED (1B-reconcile) — 1B may instead publish them inside a diet
// ConceptScheme. Reconcile before the committed dist is treated as final.

/** The canonical trigger-class slugs (DESIGN §2.2 entity 5), with evidence-prior lag profiles in `trigger.ts`. */
export const TRIGGER_SLUGS = [
  "gluten",
  "lactose",
  "fructose",
  "fructan",
  "galactan",
  "polyol",
  "sulphites",
  "histamine",
  "nuts",
  "soy",
  "egg",
  "caffeine",
] as const;

/** A canonical trigger-class slug. */
export type TriggerSlug = (typeof TRIGGER_SLUGS)[number];

/** True if `s` is one of the canonical trigger slugs. */
export function isTriggerSlug(s: string): s is TriggerSlug {
  return (TRIGGER_SLUGS as readonly string[]).includes(s);
}

/**
 * The `diet:{slug}` concept IRI for a trigger class (e.g. `diet:gluten`).
 * INVENTED (1B-reconcile): DESIGN names the slug, not the IRI form.
 */
export function triggerIri(slug: TriggerSlug): string {
  return diet(slug);
}

/**
 * The trigger slug for a `diet:{slug}` concept IRI, or `undefined` if the IRI is
 * not one of the canonical trigger concepts. The inverse of {@link triggerIri}.
 */
export function triggerSlugFromIri(iri: string): TriggerSlug | undefined {
  if (!iri.startsWith(DIET)) return undefined;
  const local = iri.slice(DIET.length);
  return isTriggerSlug(local) ? local : undefined;
}
