// AUTHORED-BY Claude Opus 4.8 (Fable unavailable) — re-review/upgrade candidate; see docs/MODEL-PROVENANCE.md
/**
 * Public-API snapshot — the reviewability cornerstone.
 *
 * Emits a single, committed, diffable `etc/solid-offline.api.md` containing the
 * FULL emitted `.d.ts` of every published entry point (`.`, `./worker`,
 * `./react`) plus the shared type chunk they import. So "what is the public API?"
 * is a one-file diff, and a contract change (a new/removed/renamed export, a
 * changed signature, an overload, OR a changed shape of any referenced type) is a
 * reviewed diff in this file — never silent.
 *
 * Snapshotting the EMITTED `.d.ts` verbatim (rather than re-deriving the surface
 * with the compiler API) is deliberate — it is the exact as-published type
 * contract, so it captures overload sets, declaration merges, and the shapes of
 * non-exported-but-referenced types (e.g. `StatusChannel` reachable via
 * `StatusSurfaceOptions`) that a name-only walk would miss. It is also far less
 * code to audit than a bespoke AST serializer, and needs no dependency beyond the
 * Node stdlib.
 *
 *   node scripts/api-report.mjs           # regenerate etc/solid-offline.api.md (after build)
 *   node scripts/api-report.mjs --check    # FAIL if the committed report is stale (a gate)
 *
 * The report is generated from `dist/*.d.ts`, so it must be regenerated AFTER
 * `npm run build`.
 */
import { spawnSync } from 'node:child_process';
import { existsSync, mkdirSync, readFileSync, readdirSync, writeFileSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const DIST = join(ROOT, 'dist');
const REPORT_PATH = join(ROOT, 'etc', 'solid-offline.api.md');

/**
 * The published entry points' `.d.ts`, DERIVED from `package.json` `exports` (not
 * hardcoded) so a new entry point is automatically represented in the snapshot —
 * its `.d.ts` is reported in the most-read first section, and a removed/renamed
 * entry shows as a report diff. Each export's `types` (e.g. `./dist/index.d.ts`)
 * is mapped to its basename.
 */
function entryDtsFromExports() {
  const pkg = JSON.parse(readFileSync(join(ROOT, 'package.json'), 'utf8'));
  const exportsField = pkg.exports ?? {};
  const out = [];
  for (const entry of Object.values(exportsField)) {
    const types = typeof entry === 'object' && entry ? entry.types : undefined;
    if (typeof types === 'string' && types.endsWith('.d.ts')) {
      out.push(types.replace(/^.*[/\\]/, '')); // basename
    }
  }
  return out;
}

/**
 * The .d.ts files to snapshot: every published entry point (from `exports`), plus
 * every OTHER `.d.ts` in dist (the shared type chunks the entries import, e.g.
 * `status-*.d.ts`). A shared chunk carries part of the public surface, so a change
 * to it must show in the report too. The entry points come first (most-read), in
 * `exports` order; then any remaining chunks, sorted so the report is stable.
 */
function dtsFiles() {
  const all = new Set(readdirSync(DIST).filter((f) => f.endsWith('.d.ts')));
  const entries = entryDtsFromExports().filter((f) => all.has(f));
  const entrySet = new Set(entries);
  const chunks = [...all].filter((f) => !entrySet.has(f)).sort();
  return [...entries, ...chunks];
}

/**
 * The chunk-import hash in `dist/status-<hash>.{js,d.ts}` is build-deterministic
 * for a given source but is otherwise an implementation detail. Normalize it to a
 * stable placeholder — in BOTH the import specifiers inside the `.d.ts` bodies AND
 * the section-heading chunk filenames — so a harmless chunk re-hash does not show
 * as a spurious public-API diff (the SHAPES, not the chunk filename, are the
 * contract). Matches the hash before either extension.
 */
function normalizeChunkHashes(text) {
  return text.replace(/status-[A-Za-z0-9_-]+(?=\.(?:d\.ts|js))/g, 'status-<chunk>');
}

function buildReport() {
  const lines = [];
  lines.push('## API Report — `solid-offline`');
  lines.push('');
  lines.push(
    '> Generated by `scripts/api-report.mjs` — the full emitted `dist/*.d.ts` (the as-published',
  );
  lines.push(
    '> type contract). Do NOT edit by hand: run `npm run build && npm run api:report`. A diff here',
  );
  lines.push('> is a deliberate, reviewed PUBLIC-API change. Chunk-hash filenames are normalized.');
  lines.push('');
  for (const file of dtsFiles()) {
    const raw = readFileSync(join(DIST, file), 'utf8');
    lines.push(`### \`dist/${normalizeChunkHashes(file)}\``);
    lines.push('');
    lines.push('```ts');
    lines.push(normalizeChunkHashes(raw).trimEnd());
    lines.push('```');
    lines.push('');
  }
  return `${lines.join('\n').trimEnd()}\n`;
}

if (!existsSync(DIST)) {
  console.error('dist/ not found — run `npm run build` before generating the API report.');
  process.exit(1);
}

const report = buildReport();
const isCheck = process.argv.includes('--check');

if (isCheck) {
  let committed = '';
  try {
    committed = readFileSync(REPORT_PATH, 'utf8');
  } catch {
    committed = '';
  }
  if (committed !== report) {
    console.error(
      'API report is stale. The public API changed (or dist was rebuilt).\n' +
        'Review the diff, then regenerate: npm run build && npm run api:report',
    );
    // Show the diff for convenience (best-effort).
    const tmp = join(ROOT, 'etc', '.solid-offline.api.expected.md');
    try {
      mkdirSync(dirname(tmp), { recursive: true });
      writeFileSync(tmp, report);
      const diff = spawnSync('git', ['--no-pager', 'diff', '--no-index', REPORT_PATH, tmp], {
        cwd: ROOT,
        encoding: 'utf8',
      });
      if (diff.stdout) console.error(diff.stdout);
    } catch {
      /* diff is best-effort */
    }
    process.exit(1);
  }
  console.log('API report matches the committed contract.');
} else {
  mkdirSync(dirname(REPORT_PATH), { recursive: true });
  writeFileSync(REPORT_PATH, report);
  console.log(`Wrote ${REPORT_PATH}`);
}
