// AUTHORED-BY Claude Opus 4.8 (Fable unavailable) — re-review/upgrade candidate.
/**
 * Interop characterization: the not-siloed memory↔chat link.
 *
 * A memory generated by a pod-chat `pc:ChatRoom` (the EXACT IRI `@jeswr/pod-chat`
 * uses — `https://w3id.org/jeswr/pod-chat#ChatRoom`, an `as:Collection`) must be
 * discoverable by a `generatedBy` search. This proves a memory written referencing
 * a real chat room is found again via that link — the whole point of reusing
 * `prov:wasGeneratedBy` rather than minting a private predicate. Deterministic, no
 * network.
 */
import { describe, expect, it } from "vitest";
import type { MemoryData } from "./memory.js";
import { parseMemoryTtl, serializeMemory } from "./memory.js";
import { searchMemories } from "./search.js";
import { PC, prov } from "./vocab.js";

const ROOM = "https://alice.pod/chat/room1#it"; // a pc:ChatRoom subject
const NOTE = "https://alice.pod/chat/2026/06/01/chat.ttl#msg-7"; // an as:Note subject

describe("memory↔chat link is found by a generatedBy search", () => {
  it("a memory generated by a pc:ChatRoom is found by generatedBy=ROOM", async () => {
    const fromRoom = await round({ text: "summary of the chat", generatedBy: ROOM });
    const fromNote = await round({ text: "a note-derived memory", generatedBy: NOTE });
    const noLink = await round({ text: "unrelated memory" });

    const found = searchMemories([fromRoom, fromNote, noLink], { generatedBy: ROOM });
    expect(found.map((m) => m.text)).toEqual(["summary of the chat"]);
  });

  it("serialized RDF carries prov:wasGeneratedBy → the pod-chat room IRI", async () => {
    const ttl = await serializeMemory("https://alice.pod/memories/m1", {
      text: "x",
      generatedBy: ROOM,
    });
    // The prov predicate + the exact pod-chat room IRI both appear.
    expect(ttl).toContain(prov("wasGeneratedBy").replace("http://www.w3.org/ns/prov#", "prov:"));
    expect(ttl).toContain(ROOM);
  });

  it("the pod-chat namespace const matches @jeswr/pod-chat's exact IRI", () => {
    // Guard: if this ever drifts from pod-chat's namespace the link silently breaks.
    expect(PC).toBe("https://w3id.org/jeswr/pod-chat#");
  });
});

/** build → serialize → parse, returning the round-tripped data (proves on-wire link survives). */
async function round(data: MemoryData): Promise<MemoryData> {
  const url = "https://alice.pod/memories/m";
  const ttl = await serializeMemory(url, data);
  const parsed = await parseMemoryTtl(url, ttl, "text/turtle");
  if (!parsed) throw new Error("round-trip lost the memory");
  return parsed;
}
