// AUTHORED-BY Codex GPT-5

import { basename } from "node:path";
import type { PropertyModel, SectorModel, ShapeModel } from "./model.ts";
import { namespaceConstantName } from "./names.ts";

const HEADER = `// AUTHORED-BY Codex GPT-5
// Generated by @jeswr/federation-codegen. DO NOT EDIT BY HAND.
`;

function jsString(value: string): string {
  return JSON.stringify(value);
}

function emitProperty(property: PropertyModel): string {
  const { accessorName, constantName, maxCount, minCount, value } = property;
  const constraint = [
    minCount > 0 ? `minCount ${minCount}` : undefined,
    maxCount === undefined ? "unbounded" : `maxCount ${maxCount}`,
    property.requiredClass === undefined ? undefined : `class <${property.requiredClass}>`,
  ]
    .filter((item) => item !== undefined)
    .join(", ");

  if (maxCount === 1 && minCount > 0) {
    return `  /** <${property.path}> (${constraint}). Structural cardinality only; domain validation is not inferred. */
  get ${accessorName}(): ${value.typescriptType} {
    return RequiredFrom.subjectPredicate(this, ${constantName}, ${value.readMapper});
  }
  set ${accessorName}(value: ${value.typescriptType}) {
    RequiredAs.object(this, ${constantName}, value, ${value.writeMapper});
  }
`;
  }

  if (maxCount === 1) {
    return `  /** <${property.path}> (${constraint}). */
  get ${accessorName}(): ${value.typescriptType} | undefined {
    return OptionalFrom.subjectPredicate(this, ${constantName}, ${value.readMapper});
  }
  set ${accessorName}(value: ${value.typescriptType} | undefined) {
    OptionalAs.object(this, ${constantName}, value, ${value.writeMapper});
  }
`;
  }

  return `  /** <${property.path}> (${constraint}). Live RDF set; minCount/class constraints require SHACL validation. */
  get ${accessorName}(): Set<${value.typescriptType}> {
    return SetFrom.subjectPredicate(
      this,
      ${constantName},
      ${value.readMapper},
      ${value.writeMapper},
    );
  }
`;
}

function emitShape(shape: ShapeModel): string {
  return `/** Typed structural projection of <${shape.shapeIri}> for <${shape.targetClass}>. */
export class ${shape.className} extends TermWrapper {
  /** rdf:type values as a live set of IRI strings. */
  get types(): Set<string> {
    return SetFrom.subjectPredicate(this, RDF_TYPE, NamedNodeAs.string, NamedNodeFrom.string);
  }

  /** Add rdf:type ${shape.className}; idempotent and chainable. */
  mark(): this {
    this.types.add(${shape.classConstantName});
    return this;
  }

  get is${shape.className}(): boolean {
    return this.types.has(${shape.classConstantName});
  }

${shape.properties.map(emitProperty).join("\n")}}
`;
}

export function emitVocab(model: SectorModel): string {
  const namespaces = Object.entries(model.prefixes)
    .filter(([prefix]) => !["owl", "prof", "rdfs", "sh", "vann"].includes(prefix))
    .sort(([left], [right]) => left.localeCompare(right))
    .map(
      ([prefix, iri]) =>
        `export const ${namespaceConstantName(prefix)} = ${jsString(iri)} as const;`,
    )
    .join("\n");
  const terms = Object.entries(model.terms)
    .sort(([left], [right]) => left.localeCompare(right))
    .map(([name, iri]) => `export const ${name} = ${jsString(iri)} as const;`)
    .join("\n");
  const prefixEntries = Object.entries(model.prefixes)
    .filter(([prefix]) => !["owl", "prof", "rdfs", "sh", "vann"].includes(prefix))
    .sort(([left], [right]) => left.localeCompare(right))
    .map(([prefix, iri]) => {
      const key = /^[A-Za-z_$][\w$]*$/.test(prefix) ? prefix : JSON.stringify(prefix);
      return `  ${key}: ${jsString(iri)},`;
    })
    .join("\n");

  return `${HEADER}
/** Namespace constants discovered from the ontology and SHACL source prefixes. */
${namespaces}

/** Class and predicate IRIs used by the generated structural model. */
${terms}

export const PREFIXES = {
${prefixEntries}
} as const;
`;
}

export function emitModel(model: SectorModel): string {
  const constants = new Set(["RDF_TYPE"]);
  for (const shape of model.shapes) {
    constants.add(shape.classConstantName);
    for (const property of shape.properties) constants.add(property.constantName);
  }
  const imports = [...constants]
    .sort()
    .map((constant) => `  ${constant},`)
    .join("\n");
  return `${HEADER}
import {
  LiteralAs,
  LiteralFrom,
  NamedNodeAs,
  NamedNodeFrom,
  OptionalAs,
  OptionalFrom,
  RequiredAs,
  RequiredFrom,
  SetFrom,
  TermWrapper,
} from "@rdfjs/wrapper";
import {
${imports}
} from "./vocab.ts";

${model.shapes.map(emitShape).join("\n")}`;
}

export function emitIndex(): string {
  return `${HEADER}
export * from "./model.ts";
export * from "./vocab.ts";
`;
}

export function emitPackageJson(packageName: string): string {
  return `${JSON.stringify(
    {
      name: packageName,
      version: "0.0.0",
      private: true,
      description: "Generated bookmarks-sector RDF vocabulary and typed wrapper accessors (PoC)",
      type: "module",
      main: "./dist/index.js",
      types: "./dist/index.d.ts",
      exports: {
        ".": {
          types: "./dist/index.d.ts",
          import: "./dist/index.js",
        },
        "./ontology.ttl": "./ontology.ttl",
        "./shapes.ttl": "./shapes.ttl",
      },
      files: ["dist", "ontology.ttl", "shapes.ttl", "README.md"],
      scripts: {
        build: "tsc -p tsconfig.json",
        typecheck: "tsc -p tsconfig.json --noEmit",
      },
      dependencies: {
        "@rdfjs/wrapper": "^0.34.0",
      },
      peerDependencies: {
        "@rdfjs/types": "^2.0.1",
      },
      devDependencies: {
        "@rdfjs/types": "^2.0.1",
        typescript: "^6.0.3",
      },
      engines: {
        node: ">=20",
      },
    },
    null,
    2,
  )}\n`;
}

export function emitTsconfig(): string {
  return `{
  "compilerOptions": {
    "target": "ES2023",
    "lib": ["ES2023"],
    "module": "NodeNext",
    "moduleResolution": "NodeNext",
    "strict": true,
    "noUncheckedIndexedAccess": true,
    "noImplicitOverride": true,
    "noFallthroughCasesInSwitch": true,
    "isolatedModules": true,
    "verbatimModuleSyntax": true,
    "allowImportingTsExtensions": true,
    "rewriteRelativeImportExtensions": true,
    "declaration": true,
    "declarationMap": true,
    "sourceMap": true,
    "skipLibCheck": true,
    "rootDir": "src",
    "outDir": "dist"
  },
  "include": ["src/**/*.ts"]
}
`;
}

export function emitReadme(ontologyPath: string, shapesPath: string): string {
  return `<!-- AUTHORED-BY Codex GPT-5 -->
# Generated bookmarks-sector model (PoC)

Generated from \`${basename(ontologyPath)}\` and \`${basename(shapesPath)}\` by
\`@jeswr/federation-codegen\`. The output is a structural projection of the SHACL graph,
not a security-reviewed application model.

The accessors enforce RDF term projections and setter cardinality through
\`@rdfjs/wrapper\`. Consumers still need SHACL validation, domain-specific input checks,
fail-closed builders, and read-path hardening. Do not publish this proof-of-concept package.
`;
}
